name: MacOS

on:
  push:
  pull_request:

jobs:
  build-test-run-macos:
    name: Build & Test & Run
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update repositories
        run: brew update

      - name: Unbreak python in github actions
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
          sudo rm -rf /Library/Frameworks/Python.framework/
          brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3

      - name: Install meson build system
        run: python3 -m pip install meson

      - name: Install ninja build system
        run: brew install ninja

      - name: Configure build directory for shared library
        run: meson setup builddir -Dtests=true -Dexamples=true -Ddefault_library=shared

      - name: Compile project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir

      - name: Start example
        run: builddir/examples/example --help

      - name: Start single header example
        run: builddir/examples/example-single-header --help

      - name: Configure build directory for static library
        run: meson configure builddir -Dtests=true -Dexamples=true -Ddefault_library=static

      - name: Compile project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir

      - name: Start example
        run: builddir/examples/example --help

      - name: Start single header example
        run: builddir/examples/example-single-header --help
